language: c
compiler: gcc

os: linux
dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_script:
  - cmake --version
  - sudo apt install -y gcc make gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
  - mkdir build
  - cd build
  - sed -i '6d' ../externals/pico-sdk/src/rp2_common/pico_standard_link/CMakeLists.txt

script:
  - cmake -DBMP280_DRIVER_BUILD_EXAMPLE=ON ..
  - make