language: c
compiler: gcc

os: windows
before_script:
  - cd externals/pico-sdk/src/rp2_common/pico_standard_link
  #- get-content CMakeLists.txt | %{$_ -replace "new_delete.cpp","new_delete.c"} > _CMakeLists.txt
  #- mkdir old
  #- move CMakeLists.txt old/CMakeLists.txt
  #- ren _CMakeLists.txt CMakeLists.txt
  #- echo "#define FAKE_NEW_DELETE_C_RASPBERRY_TELL_ME_WHY" > new_delete.c
  - wget -UseBasicParsing https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.07/gcc-arm-none-eabi-10.3-2021.07-win32.zip -o gcc-arm-none-eabi-bin.zip
  - Expand-Archive gcc-arm-none-eabi-bin.zip -DestinationPath gcc-arm-none-eabi-bin
  - sed -i '6d' CMakeLists.txt
  - cd ../../../../../
  - choco upgrade cmake
  - mkdir build
  - cd build

script:
  - cmake -DBMP280_DRIVER_BUILD_EXAMPLE=ON ..
  - mingw32-make