language: c
compiler: gcc

os: windows
before_script:
  - cd externals/pico-sdk/src/rp2_common/pico_standard_link
  - cd ../../../../../
  - wget --no-check-certificate https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.07/gcc-arm-none-eabi-10.3-2021.07-win32.zip
  - unzip gcc-arm-none-eabi-10.3-2021.07-win32.zip gcc-arm-none-eabi-10.3-2021.07-win32
  #- export PATH=$TRAVIS_BUILD_DIR/gcc-arm-none-eabi-10.3-2021.07-win32/bin$PATH
  - sed -i '6d' CMakeLists.txt
  - choco upgrade cmake
  - mkdir build
  - cd gcc-arm-none-eabi-10.3-2021.07-win32 ###
  - dir ###
  - cd build

script:
  - cmake -DPICO_TOOLCHAIN_PATH="gcc-arm-none-eabi-10.3-2021.07-win32/bin" -G"MinGW Makefiles" -DBMP280_DRIVER_BUILD_EXAMPLE=ON ..
  - mingw32-make
