language: c
compiler: gcc

os: Windows

addons:
  packages:
    xpm

before_script:
  - npm install --global xpm@latest
  - xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@latest --verbose
  - choco upgrade cmake
  - mkdir build
  - cd build
  - sed -i '6d' ../externals/pico-sdk/src/rp2_common/pico_standard_link/CMakeLists.txt

script:
  - cmake -G"MinGW Makefiles" -DBMP280_DRIVER_BUILD_EXAMPLE=ON ..
  - mingw32-make