language: c
compiler: gcc

os: windows
before_script:
  - cd externals/pico-sdk/src/rp2_common/pico_standard_link
  - get-content CMakeLists.txt | %{$_ -replace "new_delete.cpp","new_delete.c"} > _CMakeLists.txt
  - mkdir old
  - move CMakeLists.txt old/CMakeLists.txt
  - ren _CMakeLists.txt CMakeLists.txt
  - echo "#define FAKE_NEW_DELETE_C_RASPBERRY_TELL_ME_WHY" > new_delete.c
  - cd ../../../../../
  - choco upgrade cmake
  - mkdir build
  - cd build

script:
  - cmake -DBMP280_DRIVER_BUILD_EXAMPLE=ON ..
  - mingw32-make