language: c
compiler: gcc

os: windows
before_script:
  - choco upgrade cmake
  - type externals/pico-sdk/src/rp2_common/pico_standard_link/CMakeLists.txt | findstr /v new_delete.cpp
  - mkdir build
  - cd build

script:
  - cmake -DBMP280_DRIVER_BUILD_EXAMPLE=ON ..
  - make